services:
  server:
    container_name: server
    build: 
      context: .
    ports:
      - 4000:4000

  db:
    platform: linux/x86_64
    container_name: db
    image: mysql:8.0
    restart: always
    ports:
      - 5432:5432
    environment:
      MYSQL_DATABASE: ${DB_NAME} 
      MYSQL_ROOT_PASSWORD: ${DB_USER_PASSWORD}
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080