services:
  server:
    container_name: server
    build: 
      context: .
    ports:
      - 4000:4000

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER_USER} 
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080