services:
  server:
    container_name: server
    build: 
      context: .
    ports:
      - 4000:4000


  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080